services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ./pia.env
    environment:
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: openvpn
      SERVER_REGIONS: "${PIA_LOC:-Switzerland}"
      PORT_FORWARD_ONLY: "on"
      VPN_PORT_FORWARDING: "on"
      VPN_PORT_FORWARDING_STATUS_FILE: /tmp/gluetun/forwarded_port
      VPN_PORT_FORWARDING_UP_COMMAND: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
      OPENVPN_PROTOCOL: udp
      PUID: "1000"
      PGID: "1000"
      TZ: America/Los_Angeles
    volumes:
      - ./config/gluetun:/gluetun
    ports:
      - 8080:8080/tcp
      - 8082:8082/tcp
      - 5299:5299/tcp
      - 9696:9696/tcp
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Los_Angeles
      WEBUI_PORT: "8080"
      UMASK: "002"
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/stuff/Downloads:/downloads
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: America/Los_Angeles
      PORT: "13378"
      HOST: "0.0.0.0"
    user: "1000:1000"
    volumes:
      - ./config/audiobookshelf/config:/config
      - ./config/audiobookshelf/metadata:/metadata
      - /mnt/stuff/Downloads:/audiobooks
